### ISSUE TITLE
When deployed I am detected 

### ISSUE THREAD

**Issue by Louvivien** [ugorsahin/TalkingHeads#14]
Hey
Thanks for this code. It works locally but when I deploy it I get detected by Cloudflare.  It says I have been blocked. I think it is related to the IP. Did you get that?

**Comment by ugorsahin** [comment]
Cloudflare uses various types of information to understand whether you are a bot or a human. For example, if you use VPN + automation browser you will likely be marked as a bot. I assume by deploying you mean you are running it on a cloud machine or similar, which might send the wrong signals to bot protection on top of automation.

**Comment by Louvivien** [comment]
So it must be that they detect that IP comes from Vercel or Google Cloud so they block the IP I guess?

**Comment by ugorsahin** [comment]
I don't think this is about the location of IP address, my personal experience is that cloudflare can detect whether traffic comes from which cloud & service. Of course you can try forwarding the traffic which may help.
