### ISSUE TITLE
May you support "continue with Google" login option?

### ISSUE THREAD

**Issue by Sino-Huang** [ugorsahin/TalkingHeads#15]
Good day, it seems that you are not able to use other login methods such as Google, Microsoft etc.

**Comment by ugorsahin** [comment]
Yes, they are harder to automate due to a number of reasons (captcha, 2FA, obfuscation etc.). However, I can let the login function customizable, and then provide you a starting point where you can continue from.

**Comment by ugorsahin** [comment]
This issue is closed since a feature request ticket is created.
