### ISSUE TITLE
Error while running the program

### ISSUE THREAD

**Issue by Tanmay182003** [ugorsahin/TalkingHeads#16]
I am running into this error (using windows). It is because of the version of my Chrome not being compatible?

**Comment by ugorsahin** [comment]
Your current driver version is 114. Please pass `driver_version=114` to constructor, it should be fine.

**Comment by Tanmay182003** [comment]
I am getting the same error even if I pass in the driver_version=114 to the constructor of ChatGPT_Client.

**Comment by ugorsahin** [comment]
1) your email and password is visible on the image. I suggest removing the image and change your password.
2) you can explicitly pass the chromedriver path, which may solve your issue.

**Comment by ugorsahin** [comment]
No, Google SSO is not yet supported.

Can you try `headless=False`, perhaps that can solve the problem.

**Comment by gexinworks** [comment]
Can you try `headless=new`, perhaps that can solve the problem.

**Comment by ugorsahin** [comment]
Closed due to inactivity
