### ISSUE TITLE
[FEATURE] Perserve cookies

### ISSUE THREAD

**Issue by Nriver** [ugorsahin/TalkingHeads#17]
Is it possible to retain the login cookies and utilize them for subsequent script executions, rather than having to log in each time?

**Comment by ugorsahin** [comment]
Hello Nriver, it may be helpful to login once and then using the cookies. When they first published the ChatGPT, there are a few repositories out there using this approach, but then some of them switched to API instead of using cookies and automation. 

Anyway, I will take a look at it.

**Comment by Nriver** [comment]
Thanks!

**Comment by ugorsahin** [comment]
Hello, you can now pass user_data_dir and set your profile, therefore skipping the login every time. Please take a look at FAQ
