### ISSUE TITLE
Cant work on command-line CentOS 8 system

### ISSUE THREAD

**Issue by mabooooo** [ugorsahin/TalkingHeads#29]
I'm running this code on a command-line CentOS 8 system, using Chrome 112 with headless mode enabled. However, I'm consistently facing login issues. The process seems to get stuck at the following point. 
I'm wondering if there's any way to provide assistance in resolving this? 
Your help would be greatly appreciated!!!!

  File "/root/gptAuto/main.py", line 3, in <module>
    chatgpt = ChatGPT_Client(XXX,XXX)
  File "/usr/local/lib/python3.9/site-packages/chatgpt_automation/chatgpt_client.py", line 88, in __init__
    self.pass_verification()
  File "/usr/local/lib/python3.9/site-packages/chatgpt_automation/chatgpt_client.py", line 111, in pass_verification
    time.sleep(1)

**Comment by ugorsahin** [comment]
Hey,

Can you pass `verbose=True` to constructor and run again?

**Comment by mabooooo** [comment]
2023/08/23 13:33:44 INFO Verbose mode active
2023/08/23 13:33:44 INFO Loading undetected Chrome
2023/08/23 13:33:44 INFO The version is 112
2023/08/23 13:33:45 INFO patching driver executable /root/.local/share/undetected_chromedriver/undetected_chromedriver
2023/08/23 13:33:45 INFO Loaded Undetected chrome
2023/08/23 13:33:45 INFO Opening chatgpt


It stucked here

**Comment by ugorsahin** [comment]
By stuck, do you mean it hangs indefinitely or crashes with an error message?

**Comment by ugorsahin** [comment]
Closed due to inactivity
