### ISSUE TITLE
Unable to locate text area tag. Switching to ID search

### ISSUE THREAD

**Issue by iMusicDorian** [ugorsahin/TalkingHeads#30]
2023/08/24 00:07:44 INFO Verbose mode active
2023/08/24 00:07:44 INFO Loading undetected Chrome
2023/08/24 00:07:44 INFO patching driver executable ./chromedriver.exe
2023/08/24 00:07:44 INFO Loaded Undetected chrome
2023/08/24 00:07:44 INFO Opening chatgpt
2023/08/24 00:07:46 INFO Element //button[//div[text()="Log in"]] has found
2023/08/24 00:07:46 INFO Clicked login button
2023/08/24 00:07:48 INFO Element username has found
2023/08/24 00:07:48 INFO Filled email box
2023/08/24 00:07:48 INFO Element //button[text()="Continue"] has found
2023/08/24 00:07:50 INFO Clicked continue button
2023/08/24 00:07:50 INFO Element password has found
2023/08/24 00:07:50 INFO Filled password box
2023/08/24 00:07:53 INFO Logged in
2023/08/24 00:07:58 INFO Info screen skipped
2023/08/24 00:07:58 INFO ChatGPT is ready to interact
2023/08/24 00:07:58 INFO Unable to locate text area tag. Switching to ID search
Traceback (most recent call last):
  File "c:/Users/iMusic/Desktop/chatgpt_headless_chrome/chatgpt_automata.py", line 18, in <module>
    answer = chatgpt.interact(question="based on eva lyrics, to summarize its keywords")
  File "C:\Users\iMusic\AppData\Local\Programs\Python\Python38\lib\site-packages\chatgpt_automation\chatgpt_client.py", line 258, in interact
    raise RuntimeError('Unable to find the text prompt area. Please raise an issue with verbose=True')
RuntimeError: Unable to find the text prompt area. Please raise an issue with verbose=True

**Comment by ugorsahin** [comment]
Hey,

Can you please pass headless=False and see if the info screen is still visible? In my end, I can't reproduce the problem.

**Comment by iMusicDorian** [comment]
Oops!
You tried signing in with a different authentication method than the one you used during signup. Please try again using your original authentication method.

**Comment by iMusicDorian** [comment]
Oh, I got it, its my own problem, I register my account with google account, so it cannot log in with mailaddress and password, now I register a new account with email address and password, now it works! And one more question, can I use it to log in with google account rather than mail address and password.

**Comment by iMusicDorian** [comment]
And one more thing that can I stay in loggin state rather than each time when I use the script I need to log in again.

**Comment by ugorsahin** [comment]
I have an issue for Google SSO [here](https://github.com/ugorsahin/ChatGPT_Automation/issues/22) but I don't have time to implement it. I am not sure when I can find some time. If you would like to contribute, you can work on it.
