### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by taehaddd** [ugorsahin/TalkingHeads#36]
Hi.An error occurred while using. It remains the same even though you used the "pip install -e git+https://github.com/jdholtz/undetected-chromedriver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver " on the Issue tab. How do you want me to fix it?

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_25336/947264807.py in <module>
      1 from chatgpt_automation import ChatGPT_Client
      2 
----> 3 chatgpt = ChatGPT_Client(YOUR_USERNAME, YOUR_PASSWORD)
      4 
      5 answer = chatgpt.interact("Hello, how are you today")

~\anaconda3\lib\site-packages\chatgpt_automation\chatgpt_client.py in __init__(self, username, password, headless, cold_start, incognito, driver_executable_path, driver_arguments, driver_version, verbose)
     88         self.browser.get('https://chat.openai.com/auth/login?next=/chat')
     89         if not cold_start:
---> 90             self.pass_verification()
     91             self.login(username, password)
     92         logging.info('ChatGPT is ready to interact')

~\anaconda3\lib\site-packages\undetected_chromedriver\__init__.py in __init__(self, options, user_data_dir, driver_executable_path, browser_executable_path, port, enable_cdp_events, service_args, service_creationflags, desired_capabilities, advanced_elements, service_log_path, keep_alive, log_level, headless, version_main, patcher_force_close, suppress_welcome, use_subprocess, debug, no_sandbox, **kw)

~\anaconda3\lib\site-packages\undetected_chromedriver\patcher.py in auto(self, executable_path, force, version_main)

~\anaconda3\lib\site-packages\undetected_chromedriver\patcher.py in fetch_release_number(self)

~\anaconda3\lib\urllib\request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    212     else:
    213         opener = _opener
--> 214     return opener.open(url, data, timeout)
    215 
    216 def install_opener(opener):

~\anaconda3\lib\urllib\request.py in open(self, fullurl, data, timeout)
    521         for processor in self.process_response.get(protocol, []):
    522             meth = getattr(processor, meth_name)
--> 523             response = meth(req, response)
    524 
    525         return response

~\anaconda3\lib\urllib\request.py in http_response(self, request, response)
    630         # request was successfully received, understood, and accepted.
    631         if not (200 <= code < 300):
--> 632             response = self.parent.error(
    633                 'http', request, response, code, msg, hdrs)
    634 

~\anaconda3\lib\urllib\request.py in error(self, proto, *args)
    559         if http_err:
    560             args = (dict, 'default', 'http_error_default') + orig_args
--> 561             return self._call_chain(*args)
    562 
    563 # XXX probably also want an abstract factory that knows when it makes

~\anaconda3\lib\urllib\request.py in _call_chain(self, chain, kind, meth_name, *args)
    492         for handler in handlers:
    493             func = getattr(handler, meth_name)
--> 494             result = func(*args)
    495             if result is not None:
    496                 return result

~\anaconda3\lib\urllib\request.py in http_error_default(self, req, fp, code, msg, hdrs)
    639 class HTTPDefaultErrorHandler(BaseHandler):
    640     def http_error_default(self, req, fp, code, msg, hdrs):
--> 641         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    642 
    643 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found`

**Comment by isMMa** [comment]
try 

 pip install undetected-chromedriver

**Comment by ugorsahin** [comment]
Do you still have the problem? Please pass `verbose=True` to your constructor and share the debug output with us.

**Comment by RussQuan** [comment]
### For the ubuntu user to fix
Just go to https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/
and download 101 version then install via `sudo dpkg -i "your-chrome-file.deb"` then it works!

**Comment by ugorsahin** [comment]
closed due to inactivity
