### ISSUE TITLE
[BUG] Login Hugging Faces

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/TalkingHeads#42]
When try to log in Hugging Faces (use my username and pass), the script launch this error:

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/98dfe1e0-31ec-4d83-95fc-0d4d9f0ee3ee)

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/35ead10b-170d-4361-befa-c6549be16f2f)

**Comment by ugorsahin** [comment]
Hey, perhaps this can help you solve the problem, please take a look at https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot

**Comment by isMMa** [comment]
Yeah!

Thanks for the solution:

I added this line y my docker compose and now its works!!!

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/0b3e87ae-46f3-4744-9db6-57e289e83403)

**Comment by ugorsahin** [comment]
I'm glad that it works now!
