### ISSUE TITLE
[BUG] Answer includes ChatGPT name

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/TalkingHeads#44]
Since 1 week, the answer include ChatGPT name, corresponds to the new GPT design.

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/9f3ae53c-8a63-4433-89a3-80f30e19dead)

Chat:

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/c8c3b983-a80c-40dd-8326-102ff9dae6ed)

**Comment by ugorsahin** [comment]
Hey, with the latest commit [cbe205f](https://github.com/ugorsahin/TalkingHeads/commit/cbe205f44439af9df551d0ec92820f5bfed085ec), it should be working again. Let me know if it is working on your end so we can close this issue.

**Comment by isMMa** [comment]
Thanks, great job!
