### ISSUE TITLE
[Bug] Only return ChatGPT

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/TalkingHeads#45]
Hi, now only return the name "ChatGPT"

```python
from gpt_lib import initGPT, initHuggingChat

chathead = initGPT(username ="email_pgt", password= "pass_gpt")

answer = chathead.interact("Hello, how are you today")

print(answer)
```

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/cedbe591-46bd-4a4f-9f5c-0c09b275bdd1)

**Comment by Free-Max367** [comment]
Hello @isMMa ,

After my issue with "2023/11/27 17:55:42 ERROR It is not possible to pass verification #46", I had the same problem as you: **chathead.interact only returning the word "ChatGPT"**.

My opinion was that ChatGPT has become slower recently in displaying its response.
This is likely related to allocated resources versus the number of users, perhaps also a geographical issue.
In any case, this could explain why we only get the word "ChatGPT" in return.

I then added a pause of several seconds in the file 'chatgpt.py', function 'interact', after the line `self.wait_until_disappear(By.CLASS_NAME, self.wait_cq)`:

`        self.wait_until_disappear(By.CLASS_NAME, self.wait_cq)`
`        time.sleep(60)  # Modification Free-Max367`
`        answer = self.browser.find_elements(By.CLASS_NAME, self.chatbox_cq)[-1]`
`        logging.info('Answer is ready')`

It works well now. I get a complete response.
Yes, 60 seconds is a lot, but I have no time constraints.
However, it's clearly not the right approach, and I am confident that @ugorsahin will find a much better automation method than what I have used here.
And, I will gladly beta-test the new release if @ugorsahin does not see this response issue on their end.
Thanks in advance.

_Technical info: I'm using Windows 10 Entreprise version 22H2 + chrome-for-testing version 116.0.5845.96_

**Comment by isMMa** [comment]
Yes, now its works:

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/c3e1b2b3-bc97-42c6-9b24-31d0cb720e11)

**Comment by Free-Max367** [comment]
Hello @isMMa ,
On my end, it still doesn't work even with version 0.2.3.
To conduct the test, I ask ChatGPT to summarize a text of around 4000 characters.
In return, I get an empty text.
I still believe it's a response time issue with ChatGPT.

**Comment by Free-Max367** [comment]
Hey,
The version `0.3.0` works perfectly on my end.
Thanks.
