### ISSUE TITLE
SyntaxError: invalid decimal literal

### ISSUE THREAD

**Issue by Nsohan** [ugorsahin/TalkingHeads#57]
SyntaxError: invalid decimal literal, showing on the password field.

**Comment by ugorsahin** [comment]
Can you provide more details?

**Comment by Nsohan** [comment]
SyntaxError: invalid decimal literal

i get this error on my password.

after change password I get this error
NameError: name 'myname88' is not defined !

**Comment by ugorsahin** [comment]
This is not happening because of an error or bug in the package itself.

You may take a look at your code and try to fix your errors. SyntaxError means python interpreter fails to parse your code. NameError means you try to access a variable that doesn't exist.
