### ISSUE TITLE
Update to Gemini

### ISSUE THREAD

**Issue by Ran-Mewo** [ugorsahin/TalkingHeads#59]
Bard changed their entire branding to Gemini
so it's now https://gemini.google.com/app

**Comment by ugorsahin** [comment]
Hey, I've seen the rebranding but I couldn't find time to respond to that. I'll take a look at following days and push a commit soon.

 Cheers

**Comment by ugorsahin** [comment]
Hey, the rebranding has now reflected to the code, too. Have fun using it.
