### ISSUE TITLE
Unable to find the text prompt area. Please raise an issue with verbose=True

### ISSUE THREAD

**Issue by ishandutta2007** [ugorsahin/TalkingHeads#62]
Code:

```
from talkingheads import ChatGPTClient
chathead = ChatGPTClient(
    cold_start=True,
    incognito=False,
    headless=False,
    user_data_dir='/Users/ishandutta2007/Library/Application Support/BraveSoftware/Brave-Browser/Default'
)
answer = chathead.interact("Hello, how are you today")
print(answer)

```

Command:
```
python mycodefile.py  --verbose=True
```

Error:

> 
> Traceback (most recent call last):
>   File "index.py", line 65, in <module>
>     answer = chathead.interact("Hello, how are you today")
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/talkingheads/model_library/chatgpt.py", line 133, in interact
>     raise RuntimeError(
> RuntimeError: Unable to find the text prompt area. Please raise an issue with verbose=True

- I am facing same issue with `HuggingChatClient` as well. For Claude and Gemini the webdriver launches just fine for me to login. 
- I am on OSX 10.15
- My python version is 3.8.0

**Comment by ishandutta2007** [comment]
The thing is OpenAI login rarely works for me, so I always chose login with google which always works.

**Comment by ishandutta2007** [comment]
For HuggingChat there's an additional popup which ask you to confir . probably thats what makes the prompt box invisible.

> Traceback (most recent call last):
>   File "index.py", line 117, in <module>
>     answer = chathead.interact("Hello, how are you today")
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/talkingheads/model_library/huggingchat.py", line 85, in interact
>     text_area.send_keys(each_line)
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
>     self._execute(
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
>     return self._parent.execute(command, params)
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
>     self.error_handler.check_response(response)
>   File "/Users/ishandutta2007/.pyenv/versions/3.8.0/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
>   (Session info: chrome=122.0.6261.69)

**Comment by ugorsahin** [comment]
For HuggingChat, have you logged in the UI to accept Privacy and Terms?

For ChatGPT, it seems like you are not in the chat page but somewhere else, perhaps in robot verification page. I will take a look at that

**Comment by ishandutta2007** [comment]
@ugorsahin I use hugging chat, so I am aware of login. Just one click to accept the popup is required in case it pops up, maybe it's browser specific (I am on Brave). 

I'll try to send you a pull requests when I have time. Its simpler that way than trying to explain here.

**Comment by isMMa** [comment]
I have the same error:

![imagen](https://github.com/ugorsahin/TalkingHeads/assets/6026178/7b4a2f0d-162a-48bf-be27-4e1dbd44c76a)

**Comment by ugorsahin** [comment]
Closed due to inactivity.
