### ISSUE TITLE
TypeError: talkingheads.base_browser.BaseBrowser.__init__() got multiple values for keyword argument 'timeout_dur'

### ISSUE THREAD

**Issue by Free-Max367** [ugorsahin/TalkingHeads#70]
Hello,

Could you remove the `timeout_dur=40` parameter in the function definition `def __init__(self, **kwargs)` in **copilot.py** (talkingheads **0.5.0**)?

The Copilot of my company has rather slow response times.
I am forced to increase the duration of the `timeout_dur=180` parameter when calling the **CopilotClient** function: `chathead = CopilotClient(timeout_dur = 180, incognito = False, user_data_dir = chrome_user_data)`
I then get the error in the title of this issue and a program stop.
I suggest you remove this parameter in `def __init__(self, **kwargs)` in **copilot.py** but, of course, I leave it up to you to choose the option to retain as the designer of this program.
Looking forward to your reply ...

**Comment by ugorsahin** [comment]
Hello, I believe this may require some attention. I will fix this.
