### ISSUE TITLE
ElementClickInterceptedException: element click intercepted: Element is not clickable at point (733, 806)

### ISSUE THREAD

**Issue by Free-Max367** [ugorsahin/TalkingHeads#71]
Hello,

I feel like there's an issue with the `switch_model` function in copilot.py (talkingheads 0.5.0).

When I use this function and the display of 'Choose a conversation style' options is not visible on the web page, the error mentioned in the title of this issue occurs. Below is the traceback:

> chathead.switch_model("Precise")

> INFO:Copilot: cib-serp is located.
> INFO:Copilot: cib-conversation-main is located.
> INFO:Copilot: cib-welcome-container is located.
> INFO:Copilot: cib-tone-selector is located.
> INFO:Copilot: button is located.
> Traceback (most recent call last):
> 
>   Cell In[16], line 1
>     chathead.switch_model("Precise")
> 
>   File ~\AppData\Local\anaconda3\envs\meeting_report\Lib\site-packages\talkingheads\model_library\copilot.py:370 in switch_model
>     button.click()
> 
>   File ~\AppData\Local\anaconda3\envs\meeting_report\Lib\site-packages\selenium\webdriver\remote\webelement.py:94 in click
>     self._execute(Command.CLICK_ELEMENT)
> 
>   File ~\AppData\Local\anaconda3\envs\meeting_report\Lib\site-packages\selenium\webdriver\remote\webelement.py:395 in _execute
>     return self._parent.execute(command, params)
> 
>   File ~\AppData\Local\anaconda3\envs\meeting_report\Lib\site-packages\selenium\webdriver\remote\webdriver.py:347 in execute
>     self.error_handler.check_response(response)
> 
>   File ~\AppData\Local\anaconda3\envs\meeting_report\Lib\site-packages\selenium\webdriver\remote\errorhandler.py:229 in check_response
>     raise exception_class(message, screen, stacktrace)
> 
> ElementClickInterceptedException: element click intercepted: Element is not clickable at point (733, 806)
>   (Session info: chrome=124.0.6367.119)

![image](https://github.com/ugorsahin/TalkingHeads/assets/141436445/65fe5bab-7383-48b4-8546-07ae64fb4afd)

When the display of 'Choose a conversation style' options is visible on the web page, the function runs correctly.

> chathead.switch_model("Precise")

> INFO:Copilot: cib-serp is located.
> INFO:Copilot: cib-conversation-main is located.
> INFO:Copilot: cib-welcome-container is located.
> INFO:Copilot: cib-tone-selector is located.
> INFO:Copilot: button is located.
> INFO:Copilot:Switched to Precise
> Out[17]: True

![image](https://github.com/ugorsahin/TalkingHeads/assets/141436445/0ee2fedc-bae2-46d0-8727-e1ac7dd7fff0)

Looking forward to your feedback...

**Comment by ugorsahin** [comment]
The reworked version of Copilot should work.
