### ISSUE TITLE
GPT: Site has new design with new elements

### ISSUE THREAD

**Issue by lebedynskyi** [ugorsahin/TalkingHeads#72]
Chat GPT now has new ids and attributes.

Login button changed -> "login_xq"      : "//button[//span[text()='Log in']]",
Send button changed -> "send_btn_xq"   : "//button[@data-testid='fruitjuice-send-button']",
Stop generating changed -> "wait_xq"       : "//button[@data-testid='fruitjuice-stop-button']",

**Comment by ugorsahin** [comment]
Hey,

You can switch to the may_fixes branch for now. It includes a fix for the ChatGPT button changes.
