### ISSUE TITLE
[BUG] INFO:ChatGPT:Waiting element //button[//div[text()='Log in']] to appear. AND Max retries exceeded with url: /session

### ISSUE THREAD

**Issue by isMMa** [ugorsahin/TalkingHeads#74]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=57845): Max retries exceeded with url: /session/g56433e3ferfr4343e3d/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa84ef63f90>: Failed to establish a new connection: [Errno 111] Connection refused'))

INFO:ChatGPT:Loaded undetected Chrome
INFO:ChatGPT:Opening ChatGPT
INFO:ChatGPT:The preload behavior is not implemented
INFO:ChatGPT:Waiting element //button[//div[text()='Log in']] to appear.

**Comment by ugorsahin** [comment]
Connection errors fall outside the scope of this repository, so I’ll be closing this issue.
