### ISSUE TITLE
Large text does't paste very well

### ISSUE THREAD

**Issue by pritamghanghas** [ugorsahin/TalkingHeads#75]
I use this with my gemini account. I can paste fairly large text into the browser while using it manually.
But when I use talking head module, sometimes the lib gets lost with even 15 lines. It just gets stuck and never clicks the send button. 

I have no experience with selenium. It might be something with my setup alone.

**Comment by ugorsahin** [comment]
Hello, apologies for the delayed response.

In order to investigate this issue, it would be great if you could kindly provide the logs next time you encounter this problem. It’s possible that this might be a problem regarding  Selenium, but I’d like to examine the logs to confirm.
